### ISSUE TITLE
** (Protobuf.DecodeError) wrong wire_type for field start_time: got 0, expected 2

### ISSUE THREAD

**Issue by gmorell** [elixir-protobuf/protobuf#232] opened 2021-12-10 21:27 UTC
Similarly to #155, I'm getting an error while attempting to decode a protobuf. 

I compiled the module from https://developers.google.com/transit/gtfs-realtime/gtfs-realtime.proto as per the README, Took one of the generated modules to try it out and got the error from the summary. I then proceeded to find additional urls to ensure that my provider wasn't outputting incorrect data and was able to recreate it for all of them. I'm not quite familiar with protobufs to know how to proceed here.

```
url1 = "https://cdn.mbta.com/realtime/TripUpdates.pb"
url2 = "http://api.bart.gov/gtfsrt/tripupdate.aspx"
url3 = "https://s3.amazonaws.com/commtrans-realtime-prod/tripupdates.pb"
HTTPoison.get!(url1, [], [follow_redirect: true]).body
|> TransitRealtime.TripUpdate.decode()

** (Protobuf.DecodeError) wrong wire_type for field start_time: got 0, expected 2
    (protobuf 0.9.0) lib/protobuf/decoder.ex:160: Protobuf.Decoder.handle_value/6
    (protobuf 0.9.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
    (protobuf 0.9.0) lib/protobuf/decoder.ex:199: Protobuf.Decoder.value_for_field/3
    (protobuf 0.9.0) lib/protobuf/decoder.ex:359: Protobuf.Decoder.update_in_message/3
    (protobuf 0.9.0) lib/protobuf/decoder.ex:147: Protobuf.Decoder.handle_value/6
    (protobuf 0.9.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
```

**Comment by whatyouhide** [comment] 2021-12-11 07:30
Thank you @gmorell. I can reproduce the error with the first file taken from <https://cdn.mbta.com/realtime/TripUpdates.pb>. However, it's hard to say if the file was actually encoded correctly. Do you have examples of the binary there being decodable with other Protobuf libraries, to confirm it's a well-formed encoded Protobuf payload?

**Comment by ahamez** [comment] 2021-12-14 13:15
Hi there, the reason you cannot decode as a `TripUpdate` is most certainly because it's not this definition at the top-level of the protobuf binary file, but rather a `FeedMessage`. The following works for me:

```elixir
url3 = "https://s3.amazonaws.com/commtrans-realtime-prod/tripupdates.pb"
HTTPoison.get!(url3, [], [follow_redirect: true]).body
|> TransitRealtime.FeedMessage.decode()
```

**Comment by whatyouhide** [comment] 2021-12-14 19:46
Yep, I assume the same. Closing this issue for now, thanks for the suggestion @ahamez! If this still creates problems, feel free to comment down here 🙃

**Closed by whatyouhide** 2021-12-14 19:46 UTC
Labels: bug

**Comment by gmorell** [comment] 2021-12-14 19:50
Doh, thanks for the help.
