### ISSUE TITLE
How to access third-party options

### ISSUE THREAD

**Issue by sleipnir** [elixir-protobuf/protobuf#125] opened 2020-07-26 03:04 UTC
how can I access the options defined in a proto file?
I have the following proto file:

```
syntax = "proto3";

import "google/protobuf/empty.proto";
import "cloudstate/entity_key.proto";
import "google/api/annotations.proto";
import "google/api/http.proto";

package com.example.shoppingcart;

message AddLineItem {
    string user_id = 1 [(.cloudstate.entity_key) = true];
    string product_id = 2;
    string name = 3;
    int32 quantity = 4;
}

message RemoveLineItem {
    string user_id = 1 [(.cloudstate.entity_key) = true];
    string product_id = 2;
}

message GetShoppingCart {
    string user_id = 1 [(.cloudstate.entity_key) = true];
}

message LineItem {
    string product_id = 1;
    string name = 2;
    int32 quantity = 3;
}

message Cart {
    repeated LineItem items = 1;
}

service ShoppingCart {
    rpc AddItem(AddLineItem) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            post: "/cart/{user_id}/items/add",
            body: "*",
        };
    }

    rpc RemoveItem(RemoveLineItem) returns (google.protobuf.Empty) {
        option (google.api.http).post = "/cart/{user_id}/items/{product_id}/remove";
    }

    rpc GetCart(GetShoppingCart) returns (Cart) {
        option (google.api.http) = {
          get: "/carts/{user_id}",
          additional_bindings: {
            get: "/carts/{user_id}/items",
            response_body: "items"
          }
        };
}
```
How do I access the options defined in the fields and services in this file?

Thanks

**Comment by sleipnir** [comment] 2020-07-27 22:22
ping...

**Comment by sleipnir** [comment] 2020-07-30 16:26
ping...

**Comment by whatyouhide** [comment] 2020-07-30 16:30
@sleipnir I will not have time to look into this anytime soon and it looks like @tony612 doesn't have time either. We'll get to it as soon as we can, no need for pinging :) Thanks!

**Comment by sleipnir** [comment] 2020-07-30 17:05
@whatyouhide Sorry for pinging I didn't know how active this repository was. Now that I know I will wait or look for alternatives. Thank you

**Comment by whatyouhide** [comment] 2021-11-04 07:17
Closing as this is essentially a duplicate of https://github.com/elixir-protobuf/protobuf/issues/138 now. 🙃

**Closed by whatyouhide** 2021-11-04 07:17 UTC
Labels: duplicate
