### ISSUE TITLE
Dialyzer issue "Callback info about the Protobuf behaviour is not available"

### ISSUE THREAD

**Issue by yordis** [elixir-protobuf/protobuf#275] opened 2022-05-20 09:02 UTC
Hey peeps, I recently ran a the `protoc` with the elixir plugin and I am getting the following error running `mix dialyzer`:

```
________________________________________________________________________________
lib/protobuf.ex:573:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
lib/protobuf.ex:581:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
lib/protobuf.ex:599:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
lib/protobuf.ex:604:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
lib/protobuf.ex:609:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
lib/protobuf.ex:628:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
lib/protobuf.ex:652:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
lib/protobuf.ex:669:callback_info_missing
Callback info about the Protobuf behaviour is not available.
________________________________________________________________________________
```

Here is my dialyzer configuration:

```elixir
defp dialyzer do
  [plt_add_deps: :apps_direct, plt_add_apps: []]
end
```

Beside that I haven't done much.

Please let me know what other information I can share with you to help me to fix it or something.

Cheers,

**Comment by yordis** [comment] 2022-05-27 04:31
Also, scrolling upward even further, I discovered the following issues as well as part of the output:

```
________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:165:unknown_type
Unknown type: Protobuf.MessageProps.t/0.
            ________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:165:unknown_type
Unknown type: Protobuf.Wire.Types.wire_type/0.
________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:178:unknown_type
Unknown type: Protobuf.MessageProps.t/0.
            ________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:178:unknown_type
Unknown type: Protobuf.Wire.Types.wire_type/0.
________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:185:unknown_type
Unknown type: Protobuf.MessageProps.t/0.
            ________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:185:unknown_type
Unknown type: Protobuf.Wire.Types.wire_type/0.
________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:194:unknown_type
Unknown type: Protobuf.MessageProps.t/0.
            ________________________________________________________________________________
lib/myapp/protos/vault_kernel_core_api_proto_v1_contract_modules_core_api_contract_modules_core_api_contract_modules.pb.ex:194:unknown_type
Unknown type: Protobuf.Wire.Types.wire_type/0.
```

**Comment by yordis** [comment] 2022-05-27 04:38
Also,

```
lib/protobuf.ex:47: Unknown function 'Elixir.Protobuf.Builder':new/1
lib/protobuf.ex:52: Unknown function 'Elixir.Protobuf.Builder':new/2
lib/protobuf.ex:57: Unknown function 'Elixir.Protobuf.Builder':'new!'/2
lib/protobuf.ex:68: Unknown function 'Elixir.Protobuf.Decoder':decode/2
lib/protobuf.ex:71: Unknown function 'Elixir.Protobuf.Encoder':encode/1
```

**Comment by yordis** [comment] 2022-05-27 06:16
I keep turning things off and this happens:

```
lib/my_app/my_app.ex:28:unknown_function
Function Protobuf.JSON.decode!/2 does not exist.
```

**Comment by ericmj** [comment] 2022-05-29 08:14
> I keep turning things off and this happens:

What do you mean by "turning things off"? The functions dialyzer say are unknown are existing, public functions.

**Comment by yordis** [comment] 2022-05-29 18:18
@ericmj I meant to add an entry to my `.dialuzer_ignore.exs`

```elixir
[
  # TODO: remove this once https://github.com/elixir-protobuf/protobuf/issues/275 is fixed
  ~r/lib\/protobuf\.ex/, # because I turned this one off
  ~r/\/thought_machine\/protos\//, # I had to turn this  one off
  ~r/Function Protobuf\.JSON\.decode\!/ # and this other one 
]
```

```elixir
  defp dialyzer do
    [
      plt_add_deps: :apps_direct,
      plt_add_apps: [],
      ignore_warnings: ".dialyzer_ignore.exs"
    ]
  end
```

**Comment by ericmj** [comment] 2022-06-06 11:34
I cannot reproduce the errors you are seeing and they are strange because they point to lines that doesn't exist and say that functions that definitely exist doesn't exist. I get some dialyzer errors that can probably fixed but they don't look at all like yours.

There is probably an issue with your compiled modules or PLT files. I am closing this because I cannot reproduce the issue and it's unlikely to be an issue with this project. If you have more information feel free to add to this issue.

**Closed by ericmj** 2022-06-06 11:34 UTC
Labels: Kind:Bug

**Comment by yordis** [comment] 2022-06-07 03:50
Leaving some notes here since @ericmj mentioning that the line doesn't even exists led me to dig around the code.

I had the following `Makefile` command with some comment:

```makefile
protoc-install-elixir-plugin:
	# TODO: waiting for https://github.com/elixir-protobuf/protobuf/pull/255 to be released
	# mix escript.install hex protobuf
	mix escript.install github elixir-protobuf/protobuf branch main
```

So I had the protobuf for `"0.10.1-dev"` after installing the version from hex:

```shell
mix escript.install hex protobuf
```

The issue went away.

My apologies for the issue, thank you so much for the help.
