### ISSUE TITLE
Add support for optional keyword (it is in proto3 since release 3.1)

### ISSUE THREAD

**Issue by jonathantawfik** [elixir-protobuf/protobuf#156] opened 2021-05-26 02:38 UTC
When trying to include optional fields in a proto3 message I get this error :
proto/pns.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-elixir hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--elixir_out:

**Comment by whatyouhide** [comment] 2021-06-07 13:49
Closing since this is a duplicate of #104. Thanks @jonathantawfik! 💟

**Closed by whatyouhide** 2021-06-07 13:49 UTC
