### ISSUE TITLE
Unexpected default values

### ISSUE THREAD

**Issue by 21it** [elixir-protobuf/protobuf#93] opened 2020-04-01 11:41 UTC
```protobuf
message Foo {
  repeated uint32 xs = 1;
}
```

atm produces

```elixir
iex> %Foo{}
%Foo{xs: nil}
```

but expected

```elixir
iex> %Foo{}
%Foo{xs: []}
```

**Comment by jahell** [comment] 2020-04-02 06:18
> You should use YourModule.new instead of using the struct directly because default values will be set for all fields.

`Foo.new` should give you the expected default values.

Still might be worth leaving open as the code generation could add the correct default values to `defstruct`s to make it work with the `%Foo{}` syntax as well.

**Comment by tkachuk-labs** [comment] 2020-04-02 14:20
Thanks, I'm aware of `new` function, it's just not powerful enough:

```elixir
# this compiles happily 
Foo.new(banana: 123)

# this is smart enough to recognise wrong name
%Foo{banana: 123}
```

In protobuf standard field names can be changed safely, because only integer indexes matters. And this happens, which will make refactoring of code where `new` is used unpleasant as hell. The best alternative will be to combine both constructors like this

```elixir
defmodule Foo do
  defstruct xs: []

  defmacro mk_new(xs) do
    {:%, [],
     [
       {:__aliases__, [alias: false], __MODULE__},
       {:%{}, [], Enum.map(xs, &mk_smart_cons/1)}
     ]}
  end

  defp mk_smart_cons({k, x}) do
    #
    # TODO : use protobuf introspection
    #
    v =
      case k do
        :xs ->
          quote do
            x = unquote(x)
            true = is_list(x)
            x
          end
      end

    {k, v}
  end
end
```

**Comment by jahell** [comment] 2020-06-04 20:18
@tkachuk-labs there is actually `.new!` that supports compile errors for fields that are non-existent: https://github.com/tony612/protobuf-elixir/blob/e1d4a23baa1f51c2da58db24f58a26dc4d6511b2/lib/protobuf.ex#L53

**Comment by whatyouhide** [comment] 2021-11-04 07:21
@britto did we happen to fix this recently?

**Comment by britto** [comment] 2021-11-04 17:58
> did we happen to fix this recently?

We haven't.

> Or is this #95?

The original issue regarding struct defaults is indeed a duplicate of #95.

Comment https://github.com/elixir-protobuf/protobuf/issues/93#issuecomment-607875957 above on the other hand seems to be a different issue, about stricter type checking. The `new!` constructor will help us with typos in field names and properly raise an error when required fields are missing, but it won't check value types – for example, `Foo.new!(xs: 123)` won't raise any errors, even though we know we should expect a list of integers in the `xs` field.

**Comment by whatyouhide** [comment] 2021-11-06 21:46
Closing in favor of the PR #184.

**Closed by whatyouhide** 2021-11-06 21:46 UTC
Labels: enhancement
