### ISSUE TITLE
generate v7 of google ads api - optional fields problem

### ISSUE THREAD

**Issue by zivaskovic** [elixir-protobuf/protobuf#160] opened 2021-06-09 11:57 UTC
I am trying to generate v7 of google ads api. And i am getting error that says: 

google/ads/googleads/v7/errors/errors.proto:142:1: warning: Import google/api/annotations.proto is unused.
google/ads/googleads/v7/resources/currency_constant.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-elixir hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--elixir_out:

The thing that is mainly issued is this:  Please ask the owner of this code generator to support proto3 optional.--elixir_out. 

command i am using for this is: 

protoc --elixir_out=plugins=grpc:/Users/myuser/Desktop/proto  $(find /Users/myuser/myproject/googleapis/google/ads/googleads/v7 -iname "*.proto")  --proto_path=/Users/myuser/Sites/myproject/googleapis

If you could help me I would appreciate it very much!

Thank you!

**Comment by zivaskovic** [comment] 2021-06-09 12:03
In the meantime i have changed proto definitions from google and removed optional fields.

```
optional int32 end_hour = 7;
```

to

```
 int32 end_hour = 7;
````
and was able to generate v7 api for elixir but have some problems with int32 with "0" to be more precise. Other optionals work (string, boolean...)

**Comment by whatyouhide** [comment] 2021-06-11 13:39
Hey @zivaskovic , thanks for the report. Closing because this is a duplicate of https://github.com/elixir-protobuf/protobuf/issues/104.

**Closed by whatyouhide** 2021-06-11 13:39 UTC
