### ISSUE TITLE
Include `.proto` files comments as `@moduledoc` and `@doc` in generated files.

### ISSUE THREAD

**Issue by rmertzpfpt** [elixir-protobuf/protobuf#152] opened 2021-04-29 14:08 UTC
It would be nice to have comments from the `.proto` files included in the generated `.pb.ex` files when using `protoc-gen-elixir`

**Comment by whatyouhide** [comment] 2021-05-17 08:14
Closing as mostly duplicate of https://github.com/elixir-protobuf/protobuf/pull/123.

**Closed by whatyouhide** 2021-05-17 08:14 UTC
